### ISSUE TITLE
[FE] Creating doctor's dashboard

### ISSUE THREAD

**Issue by victoria-georgieva** [Kroxitrock/cancer-registry#8]
Creating doctor's dashboard. 
A Doctor should be able to:
- See examination results/edit them
- See patient's last diagnose/update it
- Check treatment process/edit  it

A doctor should see personal information and treatment processes only for the patients that are assigned to him.

**Comment by gerchevaKristina** [comment]
Sample design of the checklist:

![изображение](https://user-images.githubusercontent.com/69909872/101943589-06f96a00-3bf4-11eb-9cf5-017082e9bb95.png)
